dist: xenial
language: python

sudo: true

python:
    - "3.6"

matrix:
  allow_failures:
    - python: "3.5"

before_install:
  - sudo chmod u+x .travis/*.sh
  - /bin/bash .travis/setup.sh

script:
                               # recipe
  # - /bin/bash .travis/build.sh generic/Singularity.def

                               # recipe with tag
  #- /bin/bash .travis/build.sh --tag sneeze Singularity.tag

  # Examples with upload to storage clients defined by sregistry
  # https://singularityhub.github.io/sregistry-cli/clients
  # Environment variables must be defined in CI encrypted secrets/settings

  #- /bin/bash .travis/build.sh --uri collection/container --tag tacos --cli google-storage Singularity
  - /bin/bash .travis/build.sh --uri "https://accounts.google.com/o/oauth2/auth" --cli google-drive generic/Singularity.def
  #- /bin/bash .travis/build.sh --uri collection/container --cli globus Singularity
  #- /bin/bash .travis/build.sh --uri collection/container --cli registry Singularity
